{
 "title": "Offset Commit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_offset_commit_service_offset_commit_service_offset_commit_service_failure_rate",
     "legendFormat": "failure_rate"
    },
    {
     "expr": "kafka_monitor_offset_commit_service_offset_commit_service_offset_commit_service_failure_total",
     "legendFormat": "failure_total"
    }
   ]
  },
  {
   "title": "Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_offset_commit_service_offset_commit_service_offset_commit_service_success_rate",
     "legendFormat": "success_rate"
    },
    {
     "expr": "kafka_monitor_offset_commit_service_offset_commit_service_offset_commit_service_success_total",
     "legendFormat": "success_total"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_offset_commit_service_offset_commit_service_offset_commit_availability_avg",
     "legendFormat": "offset_commit_availability_avg"
    }
   ]
  }
 ]
}