{
 "title": "Produce",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_availability_avg",
     "legendFormat": "produce_availability_avg"
    }
   ]
  },
  {
   "title": "Delay ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_delay_ms_9999th",
     "legendFormat": "produce_delay_ms_9999th"
    },
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_delay_ms_999th",
     "legendFormat": "produce_delay_ms_999th"
    },
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_delay_ms_99th",
     "legendFormat": "produce_delay_ms_99th"
    },
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_delay_ms_avg",
     "legendFormat": "produce_delay_ms_avg"
    },
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_delay_ms_max",
     "legendFormat": "produce_delay_ms_max"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_error_rate",
     "legendFormat": "produce_error_rate"
    },
    {
     "expr": "kafka_monitor_produce_service_produce_service_produce_error_total",
     "legendFormat": "produce_error_total"
    }
   ]
  },
  {
   "title": "Records Produced",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_produce_service_records_produced_rate",
     "legendFormat": "records_produced_rate"
    },
    {
     "expr": "kafka_monitor_produce_service_produce_service_records_produced_total",
     "legendFormat": "records_produced_total"
    }
   ]
  },
  {
   "title": "Single Cluster Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_availability_avg",
     "legendFormat": "produce_availability_avg"
    }
   ]
  },
  {
   "title": "Single Cluster Delay ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_delay_ms_9999th",
     "legendFormat": "produce_delay_ms_9999th"
    },
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_delay_ms_999th",
     "legendFormat": "produce_delay_ms_999th"
    },
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_delay_ms_99th",
     "legendFormat": "produce_delay_ms_99th"
    },
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_delay_ms_avg",
     "legendFormat": "produce_delay_ms_avg"
    },
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_delay_ms_max",
     "legendFormat": "produce_delay_ms_max"
    }
   ]
  },
  {
   "title": "Single Cluster Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_error_rate",
     "legendFormat": "produce_error_rate"
    },
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_produce_error_total",
     "legendFormat": "produce_error_total"
    }
   ]
  },
  {
   "title": "Single Cluster Records Produced",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "targets": [
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_records_produced_rate",
     "legendFormat": "records_produced_rate"
    },
    {
     "expr": "kafka_monitor_produce_service_single_cluster_monitor_records_produced_total",
     "legendFormat": "records_produced_total"
    }
   ]
  }
 ]
}