{
 "title": "Commit Availability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failed Commit Offsets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_commit_availability_service_consume_service_failed_commit_offsets_avg",
     "legendFormat": "failed_commit_offsets_avg"
    },
    {
     "expr": "kafka_monitor_commit_availability_service_consume_service_failed_commit_offsets_total",
     "legendFormat": "failed_commit_offsets_total"
    }
   ]
  },
  {
   "title": "Offsets Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_commit_availability_service_consume_service_offsets_committed_total",
     "legendFormat": "offsets_committed_total"
    },
    {
     "expr": "kafka_monitor_commit_availability_service_consume_service_offsets_committed_avg",
     "legendFormat": "offsets_committed_avg"
    }
   ]
  },
  {
   "title": "Consume Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_consume_availability_avg",
     "legendFormat": "consume_availability_avg"
    }
   ]
  },
  {
   "title": "Consume Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_consume_error_rate",
     "legendFormat": "consume_error_rate"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_consume_error_total",
     "legendFormat": "consume_error_total"
    }
   ]
  },
  {
   "title": "Records Consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_consumed_total",
     "legendFormat": "records_consumed_total"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_consumed_rate",
     "legendFormat": "records_consumed_rate"
    }
   ]
  },
  {
   "title": "Records Delay ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delay_ms_999th",
     "legendFormat": "records_delay_ms_999th"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delay_ms_99th",
     "legendFormat": "records_delay_ms_99th"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delay_ms_avg",
     "legendFormat": "records_delay_ms_avg"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delay_ms_max",
     "legendFormat": "records_delay_ms_max"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delay_ms_9999th",
     "legendFormat": "records_delay_ms_9999th"
    }
   ]
  },
  {
   "title": "Records Delayed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delayed_total",
     "legendFormat": "records_delayed_total"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_delayed_rate",
     "legendFormat": "records_delayed_rate"
    }
   ]
  },
  {
   "title": "Records Duplicated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_duplicated_total",
     "legendFormat": "records_duplicated_total"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_duplicated_rate",
     "legendFormat": "records_duplicated_rate"
    }
   ]
  },
  {
   "title": "Records Lost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_lost_total",
     "legendFormat": "records_lost_total"
    },
    {
     "expr": "kafka_monitor_consume_service_consume_service_records_lost_rate",
     "legendFormat": "records_lost_rate"
    }
   ]
  },
  {
   "title": "Single Cluster Failed Commit Offsets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_commit_availability_service_single_cluster_monitor_failed_commit_offsets_avg",
     "legendFormat": "failed_commit_offsets_avg"
    },
    {
     "expr": "kafka_monitor_commit_availability_service_single_cluster_monitor_failed_commit_offsets_total",
     "legendFormat": "failed_commit_offsets_total"
    }
   ]
  },
  {
   "title": "Single Cluster Offsets Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_commit_availability_service_single_cluster_monitor_offsets_committed_total",
     "legendFormat": "offsets_committed_total"
    },
    {
     "expr": "kafka_monitor_commit_availability_service_single_cluster_monitor_offsets_committed_avg",
     "legendFormat": "offsets_committed_avg"
    }
   ]
  },
  {
   "title": "Single Cluster Consume Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_consume_availability_avg",
     "legendFormat": "consume_availability_avg"
    }
   ]
  },
  {
   "title": "Single Cluster Consume Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_consume_error_total",
     "legendFormat": "consume_error_total"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_consume_error_rate",
     "legendFormat": "consume_error_rate"
    }
   ]
  },
  {
   "title": "Single Cluster Records Consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_consumed_total",
     "legendFormat": "records_consumed_total"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_consumed_rate",
     "legendFormat": "records_consumed_rate"
    }
   ]
  },
  {
   "title": "Single Cluster Records Delay ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delay_ms_9999th",
     "legendFormat": "records_delay_ms_9999th"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delay_ms_999th",
     "legendFormat": "records_delay_ms_999th"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delay_ms_99th",
     "legendFormat": "records_delay_ms_99th"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delay_ms_avg",
     "legendFormat": "records_delay_ms_avg"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delay_ms_max",
     "legendFormat": "records_delay_ms_max"
    }
   ]
  },
  {
   "title": "Single Cluster Records Delayed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delayed_rate",
     "legendFormat": "records_delayed_rate"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_delayed_total",
     "legendFormat": "records_delayed_total"
    }
   ]
  },
  {
   "title": "Single Cluster Records Duplicated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_duplicated_rate",
     "legendFormat": "records_duplicated_rate"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_duplicated_total",
     "legendFormat": "records_duplicated_total"
    }
   ]
  },
  {
   "title": "Single Cluster Records Lost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_lost_rate",
     "legendFormat": "records_lost_rate"
    },
    {
     "expr": "kafka_monitor_consume_service_single_cluster_monitor_records_lost_total",
     "legendFormat": "records_lost_total"
    }
   ]
  }
 ]
}